// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxjbqDIM3taK_KgQl4693nqOQVNpj1Pg',
    appId: '1:704430485384:web:445bc31d1a66999b66143d',
    messagingSenderId: '704430485384',
    projectId: 'mescla-invest-5ee42',
    authDomain: 'mescla-invest-5ee42.firebaseapp.com',
    storageBucket: 'mescla-invest-5ee42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0z-FhrdD2QXH6J1iunKUUNMWabr63s4U',
    appId: '1:704430485384:android:fa57d5f0398da6e366143d',
    messagingSenderId: '704430485384',
    projectId: 'mescla-invest-5ee42',
    storageBucket: 'mescla-invest-5ee42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRto3DwSGI1DgVopyoy8tSyy9WWUbeGL8',
    appId: '1:704430485384:ios:046d95a1dda72eb666143d',
    messagingSenderId: '704430485384',
    projectId: 'mescla-invest-5ee42',
    storageBucket: 'mescla-invest-5ee42.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRto3DwSGI1DgVopyoy8tSyy9WWUbeGL8',
    appId: '1:704430485384:ios:046d95a1dda72eb666143d',
    messagingSenderId: '704430485384',
    projectId: 'mescla-invest-5ee42',
    storageBucket: 'mescla-invest-5ee42.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPxjbqDIM3taK_KgQl4693nqOQVNpj1Pg',
    appId: '1:704430485384:web:c928d5113a2884e666143d',
    messagingSenderId: '704430485384',
    projectId: 'mescla-invest-5ee42',
    authDomain: 'mescla-invest-5ee42.firebaseapp.com',
    storageBucket: 'mescla-invest-5ee42.firebasestorage.app',
  );
}
